### PR TITLE
fix double quotes escaping

### PR DESCRIPTION
**Pull request by kRaw1er**

### CODE REVIEW

**Comment by jeromegn** [comment]
Oh, this is much appreciated! :smile: 

Can you add some specs with fixtures to properly test that double quotes are escaped?

Also, the current specs seem broken, have you run them locally?

**Comment by kRaw1er** [comment]
nope, sorry. It seems my fix does not working with string interpolation. Shame on me )

**Comment by kRaw1er** [comment]
that's ok now :)

**Comment by jeromegn** [comment]
Thanks @kRaw1er 

This is not robust enough. There must be a better solution.

For instance, this valid crystal code breaks the macro:

```crystal
  span "hello #{p("#{"world"}")}"
```

```
Syntax error in expanded macro: macro_4445399120:29: Unterminated string interpolation

__str__ << HTML.escape(("\"hello #{p("#{"world"}\")}\"").to_s).to_s(__str__)
```

I had started looking at using `%()`, but I could not achieve what I wanted. Unsufficient brain power ;) It's vaguely documented here: http://crystal-lang.org/api/String.html

**Comment by jeromegn** [comment]
Oh, I didn't get notified of the changes, sorry for the delay.

I'll merge this since this is probably better than nothing :)

Thanks a ton @kRaw1er

**Pull request merged**
