### PR TITLE
Prevent = from being lost in attribute values

### PR DESCRIPTION
**Pull request by nashimoto**

### CODE REVIEW

**Comment by jeromegn** [comment]
Good catch.

Looks like I need to fix the code for crystal 0.16 to make the tests pass.

**Comment by jeromegn** [comment]
I can't fix it at the moment due to this issue: https://github.com/crystal-lang/crystal/issues/2575 a work around would be required.

I could probably enforce a crystal version for the spec for now though.

**Comment by nashimoto** [comment]
Crystal 0.17.0 released.
Passed the tests with 0.17.

**Comment by jeromegn** [comment]
I'll fix the other stuff that came up.

**Comment by nashimoto** [comment]
Thanks!!! 😄

**Pull request merged**
